### ISSUE TITLE
PublishExperiment4_Complete class need to handle "cancel" button

### ISSUE THREAD

**Issue by alivia-g** [CMPUT301W21T12/FAANG-GANG#76]
As of currently, CANCEL button is not functioning.

**Comment by csheng2** [comment]
Fixed this earlier today. Try to do a pull from master.

Issue:
- startActivity(mainActivityIntent) was in an `if clause` for just the publish button

Resolution:
- Moved startActivity(mainActivityIntent) outside of the `if clause` so that pressing "cancel" and "publish" takes the user to the mainActivity either way
